export enum SkatesActionType {
    FETCH_SKATES = 'FETCH_SKATES',
    SELECT_SKATE = 'SELECT_SKATE',
    SEARCH_FOR_SKATES_FAILED = 'SEARCH_FOR_SKATES_FAILED',
    SEARCH_FOR_SKATE = 'SEARCH_FOR_SKATE',
    CREATE_SKATE = 'CREATE_SKATE',
    CREATE_SKATE_FAILED = 'CREATE_SKATE_FAILED',
    CREATE_DISCIPLINE = 'CREATE_DISCIPLINE',
    CREATE_DISCIPLINE_FAILED = 'CREATE_DISCIPLINE_FAILED',
    CREATE_BRAND = 'CREATE_BRAND',
    CREATE_BRAND_FAILED = 'CREATE_BRAND_FAILED',
    DELETE_DISCIPLINE = 'DELETE_DISCIPLINE',
    DELETE_BRAND = 'DELETE_BRAND',
    DELETE_SKATE = 'DELETE_SKATE',
    UPDATE_SKATE = 'UPDATE_SKATE',
    UPDATE_SKATE_FAILED = 'UPDATE_SKATE_FAILED',
    FETCH_DISCIPLINES = 'FETCH_DISCIPLINES',
    FETCH_BRANDS = 'FETCH_BRANDS'
}
